### ISSUE TITLE
Kria IAS connectors require PL I2C

### ISSUE THREAD

**Issue by m-tosch** [gtaylormb/ultra96v2_imx219_to_displayport#7]
code in imx219.c uses "xiicps.h" header which is the interface to I2C element on the PS side. 
The schematic of the Kria carrier card board shows that the PS I2C elements are not connected to the camera interfaces IAS0,I AS1 and rpi camera. So at least when using the starter kit (i.e. carrier card board) a dedicated I2C inside the PL is required. Pins must be connected accordingly.

just fyi

**Comment by gtaylormb** [comment]
You can still use the PS side I2C module but route it to through the PL using EMIO pins. That's what I've done here.

I finally got my Kria board so I'll be updating the BD for it shortly (the one in the repo is currently broken).
