### ISSUE TITLE
How can we create a Vivado project?

### ISSUE THREAD

**Issue by SyunSiu** [gtaylormb/ultra96v2_imx219_to_displayport#8]
Hi @gtaylormb,

First, Thank you for sharing this project.

I am trying to create a Vivado project by your project,
but I am a new one on this, so can you tell me what should I do?

Best regards. Thank you.

**Comment by gtaylormb** [comment]
Create a new project in Vivado targeting either board and then Tools->Run Tcl Script... and select the appropriate tcl script from fpga/bd. This will import the block diagram into your project.

**Comment by SyunSiu** [comment]
Thank you very much.
